import { addDef } from '_src/defaultDefs';
import { allOfDef } from './defaultDefs/allOf';
import { anyOfDef } from './defaultDefs/anyOf';
import { constDef } from './defaultDefs/const';
import { defaultDef } from './defaultDefs/default';
import { defaultPropertiesDef } from './defaultDefs/defaultProperties';
import { deletePropertiesDef } from './defaultDefs/deleteProperties';
import { dependenciesDef } from './defaultDefs/dependencies';
import { emptyToNullDef } from './defaultDefs/emptyToNull';
import { enumDef } from './defaultDefs/enum';
import { exclusiveMaximumDef } from './defaultDefs/exclusiveMaximum';
import { exclusiveMinimumDef } from './defaultDefs/exclusiveMinimum';
import { filterItemsDef } from './defaultDefs/filterItems';
import { filterPropertiesDef } from './defaultDefs/filterProperties';
import { finiteDef } from './defaultDefs/finite';
import { ifElseDef } from './defaultDefs/ifElse';
import { instanceDef } from './defaultDefs/instance';
import { integerDef } from './defaultDefs/integer';
import { invalidDef } from './defaultDefs/invalid';
import { itemsDef } from './defaultDefs/items';
import { maximumDef } from './defaultDefs/maximum';
import { maxItemsDef } from './defaultDefs/maxItems';
import { maxLengthDef } from './defaultDefs/maxLength';
import { maxPropertiesDef } from './defaultDefs/maxProperties';
import { minimumDef } from './defaultDefs/minimum';
import { minItemsDef } from './defaultDefs/minItems';
import { minLengthDef } from './defaultDefs/minLength';
import { minPropertiesDef } from './defaultDefs/minProperties';
import { notDef } from './defaultDefs/not';
import { notEmptyDef } from './defaultDefs/notEmpty';
import { parseFloatDef } from './defaultDefs/parseFloat';
import { parseIntDef } from './defaultDefs/parseInt';
import { patternDef } from './defaultDefs/pattern';
import { propertiesDef } from './defaultDefs/properties';
import { removeDuplicateItemsDef } from './defaultDefs/removeDuplicateItems';
import { removeItemsDef } from './defaultDefs/removeItems';
import { requiredDef } from './defaultDefs/required';
import { safeIntegerDef } from './defaultDefs/safeInteger';
import { sanitizeDef } from './defaultDefs/sanitize';
import { toConstDef } from './defaultDefs/toConst';
import { toDateDef } from './defaultDefs/toDate';
import { toLocaleLowerCaseDef } from './defaultDefs/toLocaleLowerCase';
import { toLocaleUpperCaseDef } from './defaultDefs/toLocaleUpperCase';
import { toLowerCaseDef } from './defaultDefs/toLowerCase';
import { toTimestampDef } from './defaultDefs/toTimestamp';
import { toUpperCaseDef } from './defaultDefs/toUpperCase';
import { trimDef } from './defaultDefs/trim';
import { trimLeftDef } from './defaultDefs/trimLeft';
import { trimRightDef } from './defaultDefs/trimRight';
import { trimToNullDef } from './defaultDefs/trimToNull';
import { typeDef } from './defaultDefs/type';
import { uniqueItemsDef } from './defaultDefs/uniqueItems';
import { validDef } from './defaultDefs/valid';
import { validateDef } from './defaultDefs/validate';

export const addDefaultDefs = () => {
  addDef('allOf', allOfDef);
  addDef('anyOf', anyOfDef);
  addDef('const', constDef);
  addDef('default', defaultDef);
  addDef('defaultProperties', defaultPropertiesDef);
  addDef('deleteProperties', deletePropertiesDef);
  addDef('dependencies', dependenciesDef);
  addDef('emptyToNull', emptyToNullDef);
  addDef('enum', enumDef);
  addDef('exclusiveMaximum', exclusiveMaximumDef);
  addDef('exclusiveMinimum', exclusiveMinimumDef);
  addDef('filterItems', filterItemsDef);
  addDef('filterProperties', filterPropertiesDef);
  addDef('finite', finiteDef);
  addDef('ifElse', ifElseDef);
  addDef('instance', instanceDef);
  addDef('integer', integerDef);
  addDef('invalid', invalidDef);
  addDef('items', itemsDef);
  addDef('maximum', maximumDef);
  addDef('maxItems', maxItemsDef);
  addDef('maxLength', maxLengthDef);
  addDef('maxProperties', maxPropertiesDef);
  addDef('minimum', minimumDef);
  addDef('minItems', minItemsDef);
  addDef('minLength', minLengthDef);
  addDef('minProperties', minPropertiesDef);
  addDef('not', notDef);
  addDef('notEmpty', notEmptyDef);
  addDef('parseFloat', parseFloatDef);
  addDef('parseInt', parseIntDef);
  addDef('pattern', patternDef);
  addDef('properties', propertiesDef);
  addDef('removeDuplicateItems', removeDuplicateItemsDef);
  addDef('removeItems', removeItemsDef);
  addDef('required', requiredDef);
  addDef('safeInteger', safeIntegerDef);
  addDef('sanitize', sanitizeDef);
  addDef('toConst', toConstDef);
  addDef('toDate', toDateDef);
  addDef('toLocaleLowerCase', toLocaleLowerCaseDef);
  addDef('toLocaleUpperCase', toLocaleUpperCaseDef);
  addDef('toLowerCase', toLowerCaseDef);
  addDef('toTimestamp', toTimestampDef);
  addDef('toUpperCase', toUpperCaseDef);
  addDef('trim', trimDef);
  addDef('trimLeft', trimLeftDef);
  addDef('trimRight', trimRightDef);
  addDef('trimToNull', trimToNullDef);
  addDef('type', typeDef);
  addDef('uniqueItems', uniqueItemsDef);
  addDef('valid', validDef);
  addDef('validate', validateDef);
};
